language: node_js
node_js:
  - '0.12'
env:
  global:
    - secure: 0coSgcoHYGI0gRtUyJqYu0YPxSsLL4f5rw9Jd3XoJMZOE1E11UmuSjohNhWQChFrRTgqE0ykC/okV4sOzXnfKGMSiVpBqwCvkBLCIrlbDSOuMRx60MhXb17NUz9Wpm+nBOg6kqp7A0R1YMUujQzckvD4PwhI5T7zrBBzPwYjesgB8jghAJG7FdWhdCfJCXe0OBFq2HZM1U3HTzjWmvlMAtOLqn2DXtTXhHOAitgFc8cxkbtlwsdjRbN5I+rGwMFafNmuqkGYQBf1E76wM5lrUBwllCAri3pMeK1RICqkim2YfLzP9X9G1GNUbhXW1bVt+oSHxCQZSUd5MLI1LLFPXAqXhgGe+Fa9Wb6X2YpHHJyAHOHtTg4kWP8RwkcZquE1XINIrgQP/AEplMq1qjCiwGsKzFDsElXO04MWFOxzYnNTNdxLyp1QmFyq6asiYQrlSlh2TjAhSX342XKUqoTg6y63jV+TEHQ1ap3drgTHybCagOs9bcbAwP9EsPf37RNIULf2YmhaUNSDqMfghb5D1Nsjh5mrSEIHsCETlwBhU9FpePxN2rfJyCkLvjdAz4AgTWfO6Xff+46UCMGTCjT2MsURkIfwm7xxTNTdoOxTbI2JhvzHVYMCAjQVXJfX0qHIqz4DvWwH+WcWMYYPAFsmwPQFtaLH8kY+thsNGFtjsv8=
install: npm install
before_script:
  - 'git config --global user.name "Travis-CI"'
  - 'git config --global user.email "myk@mykzilla.org"'
script:
  - gulp
  - gulp test
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy'
