language: node_js
node_js:
  - '0.10'
env:
  global:
    - secure: dF195keOXo9mKATW7IZu8cJUdkp+l5w2aHQzaw8cjjaC4XWdEuMVgmTUYuX2ZB0ialAOS56J5U5Escd1r7htJYfEBsjSkBBETF5G9JxQosRyoJ5hlv5Euzja/PJByw89tNuAIjl4cGMY3KC8KK0HYrMZAO8Tb9LhDytvMW0xi1GxRr9Z6UDUwz3WrKdH4DOwwvSbUSgYDtih+FZiZyFaqEnHBRLrVvPFBIzVUInrXWn0+Co57CJMpOB0MSW5HWvmxLETMiG0Rk60AkM+LZPxIXoLWsSy0s7n6EgM3x1Mbw+dv/COd7e9N3vOpP8Wf+58AGBEhXDjaAcjRiAskVj+9cPDA8Tj4AB1cmD4MLD28sCy9U2KvK081VQrTE2kMWwBttpFOd6TexATxBgWOXifROxtKM5lzqXOrbx9Le3Aq/D7NopF2fZHOlF/T9o10cB7BVAr3LEkzR5XdcMZ7vyD7myKqKMmwbdgyyRzSQnOFiczBGWoyKn/byJjlK8dalWiZn8yrMVcSmF+FxrXA+Q7PTO6eO8Rk26WhzLx0ElTtWLK0RI5HrWeErUg5Uc1BekcWqBOZYdnbOUW/QaneaidRZ038wC+QWRDPCQiZJrUTL3T5bpisgP/DB06LzK49AVqyW9clSt8YBU1gSNGs4QuJNPcz3AvhLuiExxZQkNqyq4=
install: npm install
before_script:
  - 'git config --global user.name "Travis-CI"'
  - 'git config --global user.email "myk@mykzilla.org"'
script:
 - gulp
 - gulp test
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ] && gulp deploy'
